replicaCount: 3


image:
  repository: "us-central1-docker.pkg.dev/terraform-project-practice/artemis/artemis"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "4.0.0"



service:
  type: ClusterIP
  port: 5000


ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
  hosts:
    - host: dev-artemis.zenithcst.net
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: dev-artemis-tls
      hosts:
        - dev-artemis.zenithcst.net


